<?php

/**
 * @file
 * Contains ewp_contact.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ewp_contact_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ewp_contact module.
    case 'help.page.ewp_contact':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal implementation of the EWP Abstract Contact Type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ewp_contact_theme() {
  return [
    'ewp_contact' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function ewp_contact_theme_suggestions_org(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#contact'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'contact__' . $sanitized_view_mode;
  $suggestions[] = 'contact__' . $entity->id();
  $suggestions[] = 'contact__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
