<?php

/**
 * @file
 * Contains ewp_contact.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_help().
 */
function ewp_contact_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ewp_contact module.
    case 'help.page.ewp_contact':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal implementation of the EWP Abstract Contact Type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ewp_contact_theme($existing, $type, $theme, $path) {
  return [
    'ewp_contact' => [
      'render element' => 'children',
    ],
    'contact' => [                            // the entity id
      'path' => $path . '/templates',         // template directory in module or theme
      'template'  => 'contact',               // defines base template as /contact.html.twig
      'render element' => 'elements',         // Theme API call to define the container of the entity in the render array
                                              // The entity will be prefixed with a hash sign as ['elements']['#artwork']
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function ewp_contact_theme_suggestions_contact(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#contact'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'contact__' . $sanitized_view_mode;
  $suggestions[] = 'contact__' . $entity->id();
  $suggestions[] = 'contact__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/** @file modules/custom/ewp_contact/templates/contact.html.twig
 * Prepares variables for templates.
 * implements hook_preprocess_HOOK()
 */
function template_preprocess_contact(&$variables) {
  // Helpful $content variable for templates.
  $variables['content'] = [];
  foreach (\Drupal\Core\Render\Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  /** @var ContactEntityInterface $entity */
  $entity = $variables['elements']['#contact'];
  //provide the label
  $variables['label'] = $entity->label();
  //provide the alias
  $variables['url'] = $entity->toUrl()->toString();
  //provide the view mode
  $variables['view_mode'] = $variables['elements']['#view_mode'];
}

/**
 * Implements hook_jsonapi_entity_filter_access() for 'contact'.
 */
function ewp_contact_jsonapi_entity_filter_access(EntityTypeInterface $entity_type, AccountInterface $account) {
  return ([
    JSONAPI_FILTER_AMONG_ALL => AccessResult::allowed()
  ]);
}

/**
 * Implements hook_jsonapi_ENTITY_TYPE_filter_access() for 'contact'.
 */
function ewp_contact_jsonapi_contact_filter_access(EntityTypeInterface $entity_type, AccountInterface $account) {
  return ([
    JSONAPI_FILTER_AMONG_ALL => AccessResult::allowedIfHasPermission($account, 'view unpublished contact entities'),
    JSONAPI_FILTER_AMONG_PUBLISHED => AccessResult::allowedIfHasPermission($account, 'view published contact entities'),
    JSONAPI_FILTER_AMONG_OWN => AccessResult::allowedIfHasPermission($account, 'view published contact entities')
  ]);
}
